version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands: 
      - echo installing Mocha
      - npm install -g mocha
  pre_build: 
    commands: 
      - echo installing source NPM dependencies
      - npm install 
  build:
    commands:
      - echo Build started on `date`
      - echo compiling Node.js code
      - npm run test
  post_build: 
    commands: 
      - echo Build completed on `date`
artifacts:
  files:
    - app.js
    - package.json
    - bin/*
    - test.js